import {
  User,
  Course,
  Registration,
  Result,
  AttendanceSession,
  AttendanceRecord,
  StudentAttendanceSummary,
  TimetableSlot,
  Announcement,
  Material,
  CourseFormDoc,
} from './types';

export const CURRENT_SESSION = '2025/2026';
export const CURRENT_SEMESTER = 'First Semester';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_student_1',
    name: 'Olamide Adeleke',
    email: 'olamide.adeleke@student.mapoly.edu.ng',
    role: 'student',
    department: 'Computer Science',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    level: 'ND2',
    programme: 'Computer Science (National Diploma)',
    cgpa: 3.68,
    academicStatus: 'active',
    adviserId: 'usr_adviser_1',
    adviserName: 'Mrs. F. K. Babalola',
  },
  {
    id: 'usr_student_2',
    name: 'Babajide Ogundipe',
    email: 'babajide.ogundipe@student.mapoly.edu.ng',
    role: 'student',
    department: 'Computer Science',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    level: 'HND2',
    programme: 'Computer Science (Higher National Diploma)',
    cgpa: 3.82,
    academicStatus: 'active',
    adviserId: 'usr_adviser_2',
    adviserName: 'Engr. T. I. Ogundele',
  },
  {
    id: 'usr_student_3',
    name: 'Chidimma Nwosu',
    email: 'chidimma.nwosu@student.mapoly.edu.ng',
    role: 'student',
    department: 'Computer Science',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    matricNo: 'MAPOLY/ND/CS/2025/0015',
    level: 'ND1',
    programme: 'Computer Science (National Diploma)',
    cgpa: 3.25,
    academicStatus: 'active',
    adviserId: 'usr_adviser_1',
    adviserName: 'Mrs. F. K. Babalola',
  },
  {
    id: 'usr_lecturer_1',
    name: 'Dr. K. A. Mustapha',
    email: 'k.mustapha@mapoly.edu.ng',
    role: 'lecturer',
    department: 'Computer Science',
    staffId: 'MAP/CS/ST/042',
    title: 'Senior Lecturer',
  },
  {
    id: 'usr_adviser_1',
    name: 'Mrs. F. K. Babalola',
    email: 'f.babalola@mapoly.edu.ng',
    role: 'adviser',
    department: 'Computer Science',
    staffId: 'MAP/CS/ST/018',
    title: 'Principal Lecturer',
    adviserForLevel: 'ND2',
  },
  {
    id: 'usr_hod_1',
    name: 'Dr. A. O. Adebayo',
    email: 'hod.cs@mapoly.edu.ng',
    role: 'hod',
    department: 'Computer Science',
    staffId: 'MAP/CS/ST/001',
    title: 'Head of Department / Associate Professor',
    isHod: true,
  },
  {
    id: 'usr_admin_1',
    name: 'Engr. S. A. Folorunsho',
    email: 'admin.cs@mapoly.edu.ng',
    role: 'admin',
    department: 'Computer Science',
    staffId: 'MAP/CS/ADM/002',
    title: 'Department System Administrator',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs_101',
    code: 'COM 101',
    title: 'Introduction to Computer Systems & Operating Systems',
    unitLoad: 3,
    level: 'ND1',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: [],
    lecturerId: 'usr_lecturer_1',
    lecturerName: 'Dr. K. A. Mustapha',
    registeredCount: 142,
  },
  {
    id: 'crs_103',
    code: 'COM 103',
    title: 'Introduction to Programming Principles (C & Python)',
    unitLoad: 4,
    level: 'ND1',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: [],
    lecturerId: 'usr_adviser_1',
    lecturerName: 'Mrs. F. K. Babalola',
    registeredCount: 142,
  },
  {
    id: 'crs_201',
    code: 'COM 201',
    title: 'Data Structures & Algorithms',
    unitLoad: 3,
    level: 'ND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: ['COM 103'],
    lecturerId: 'usr_lecturer_1',
    lecturerName: 'Dr. K. A. Mustapha',
    registeredCount: 118,
  },
  {
    id: 'crs_203',
    code: 'COM 203',
    title: 'Database Design & SQL System Management',
    unitLoad: 4,
    level: 'ND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: ['COM 101'],
    lecturerId: 'usr_hod_1',
    lecturerName: 'Dr. A. O. Adebayo',
    registeredCount: 118,
  },
  {
    id: 'crs_205',
    code: 'COM 205',
    title: 'Web Application Development (HTML/CSS/JS)',
    unitLoad: 3,
    level: 'ND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: ['COM 103'],
    lecturerId: 'usr_adviser_1',
    lecturerName: 'Mrs. F. K. Babalola',
    registeredCount: 115,
  },
  {
    id: 'crs_301',
    code: 'COM 311',
    title: 'Advanced Object-Oriented Systems (Java/TypeScript)',
    unitLoad: 4,
    level: 'HND1',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: ['COM 201'],
    lecturerId: 'usr_lecturer_1',
    lecturerName: 'Dr. K. A. Mustapha',
    registeredCount: 96,
  },
  {
    id: 'crs_303',
    code: 'COM 313',
    title: 'Software Engineering & System Architecture',
    unitLoad: 3,
    level: 'HND1',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: [],
    lecturerId: 'usr_hod_1',
    lecturerName: 'Dr. A. O. Adebayo',
    registeredCount: 96,
  },
  {
    id: 'crs_401',
    code: 'COM 411',
    title: 'Distributed Systems & Cloud Computing Architecture',
    unitLoad: 4,
    level: 'HND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: ['COM 311'],
    lecturerId: 'usr_hod_1',
    lecturerName: 'Dr. A. O. Adebayo',
    registeredCount: 84,
  },
  {
    id: 'crs_403',
    code: 'COM 413',
    title: 'Computer Security & Applied Cryptography',
    unitLoad: 3,
    level: 'HND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'core',
    prerequisites: [],
    lecturerId: 'usr_lecturer_1',
    lecturerName: 'Dr. K. A. Mustapha',
    registeredCount: 84,
  },
  {
    id: 'crs_405',
    code: 'COM 415',
    title: 'Artificial Intelligence & Machine Learning Fundamentals',
    unitLoad: 3,
    level: 'HND2',
    semesterId: 'sem_1',
    semesterName: 'First Semester',
    type: 'elective',
    prerequisites: [],
    lecturerId: 'usr_adviser_1',
    lecturerName: 'Mrs. F. K. Babalola',
    registeredCount: 62,
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg_1',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    courseTitle: 'Data Structures & Algorithms',
    unitLoad: 3,
    semesterId: 'sem_1',
    status: 'approved',
    adviserApprovedAt: '2026-07-10T11:20:00Z',
    createdAt: '2026-07-08T09:15:00Z',
  },
  {
    id: 'reg_2',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_203',
    courseCode: 'COM 203',
    courseTitle: 'Database Design & SQL System Management',
    unitLoad: 4,
    semesterId: 'sem_1',
    status: 'approved',
    adviserApprovedAt: '2026-07-10T11:20:00Z',
    createdAt: '2026-07-08T09:15:00Z',
  },
  {
    id: 'reg_3',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_205',
    courseCode: 'COM 205',
    courseTitle: 'Web Application Development (HTML/CSS/JS)',
    unitLoad: 3,
    semesterId: 'sem_1',
    status: 'approved',
    adviserApprovedAt: '2026-07-10T11:20:00Z',
    createdAt: '2026-07-08T09:15:00Z',
  },
  {
    id: 'reg_4',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    courseId: 'crs_401',
    courseCode: 'COM 411',
    courseTitle: 'Distributed Systems & Cloud Computing Architecture',
    unitLoad: 4,
    semesterId: 'sem_1',
    status: 'approved',
    adviserApprovedAt: '2026-07-12T14:10:00Z',
    createdAt: '2026-07-09T10:00:00Z',
  },
  {
    id: 'reg_5',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    courseId: 'crs_403',
    courseCode: 'COM 413',
    courseTitle: 'Computer Security & Applied Cryptography',
    unitLoad: 3,
    semesterId: 'sem_1',
    status: 'approved',
    adviserApprovedAt: '2026-07-12T14:10:00Z',
    createdAt: '2026-07-09T10:00:00Z',
  },
  {
    id: 'reg_6',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    courseId: 'crs_405',
    courseCode: 'COM 415',
    courseTitle: 'Artificial Intelligence & Machine Learning Fundamentals',
    unitLoad: 3,
    semesterId: 'sem_1',
    status: 'pending',
    createdAt: '2026-07-28T16:45:00Z',
  },
];

export const INITIAL_RESULTS: Result[] = [
  {
    id: 'res_1',
    registrationId: 'reg_1',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    courseTitle: 'Data Structures & Algorithms',
    unitLoad: 3,
    caScore: 26,
    examScore: 58,
    totalScore: 84,
    grade: 'A',
    gradePoint: 4.0,
    status: 'Published',
    submittedBy: 'Dr. K. A. Mustapha',
    submittedAt: '2026-07-20T10:00:00Z',
    approvedBy: 'Dr. A. O. Adebayo',
    approvedAt: '2026-07-22T15:30:00Z',
    publishedAt: '2026-07-25T08:00:00Z',
    lastUpdated: '2026-07-25T08:00:00Z',
  },
  {
    id: 'res_2',
    registrationId: 'reg_2',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_203',
    courseCode: 'COM 203',
    courseTitle: 'Database Design & SQL System Management',
    unitLoad: 4,
    caScore: 24,
    examScore: 52,
    totalScore: 76,
    grade: 'AB',
    gradePoint: 3.5,
    status: 'Published',
    submittedBy: 'Dr. A. O. Adebayo',
    submittedAt: '2026-07-21T09:00:00Z',
    approvedBy: 'Dr. A. O. Adebayo',
    approvedAt: '2026-07-22T15:30:00Z',
    publishedAt: '2026-07-25T08:00:00Z',
    lastUpdated: '2026-07-25T08:00:00Z',
  },
  {
    id: 'res_3',
    registrationId: 'reg_3',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    courseId: 'crs_205',
    courseCode: 'COM 205',
    courseTitle: 'Web Application Development (HTML/CSS/JS)',
    unitLoad: 3,
    caScore: 28,
    examScore: 61,
    totalScore: 89,
    grade: 'A',
    gradePoint: 4.0,
    status: 'Approved',
    submittedBy: 'Mrs. F. K. Babalola',
    submittedAt: '2026-07-24T14:20:00Z',
    approvedBy: 'Dr. A. O. Adebayo',
    approvedAt: '2026-07-26T10:00:00Z',
    lastUpdated: '2026-07-26T10:00:00Z',
  },
  {
    id: 'res_4',
    registrationId: 'reg_4',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    courseId: 'crs_401',
    courseCode: 'COM 411',
    courseTitle: 'Distributed Systems & Cloud Computing Architecture',
    unitLoad: 4,
    caScore: 25,
    examScore: 59,
    totalScore: 84,
    grade: 'A',
    gradePoint: 4.0,
    status: 'Published',
    submittedBy: 'Dr. A. O. Adebayo',
    submittedAt: '2026-07-20T11:00:00Z',
    approvedBy: 'Dr. A. O. Adebayo',
    approvedAt: '2026-07-22T15:30:00Z',
    publishedAt: '2026-07-25T08:00:00Z',
    lastUpdated: '2026-07-25T08:00:00Z',
  },
  {
    id: 'res_5',
    registrationId: 'reg_5',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    courseId: 'crs_403',
    courseCode: 'COM 413',
    courseTitle: 'Computer Security & Applied Cryptography',
    unitLoad: 3,
    caScore: 22,
    examScore: 49,
    totalScore: 71,
    grade: 'B',
    gradePoint: 3.0,
    status: 'Submitted',
    submittedBy: 'Dr. K. A. Mustapha',
    submittedAt: '2026-07-26T16:00:00Z',
    lastUpdated: '2026-07-26T16:00:00Z',
  },
];

export const INITIAL_ATTENDANCE_SUMMARY: StudentAttendanceSummary[] = [
  {
    courseId: 'crs_201',
    courseCode: 'COM 201',
    courseTitle: 'Data Structures & Algorithms',
    totalClasses: 14,
    attendedClasses: 13,
    percentage: 92.8,
    isEligible: true,
  },
  {
    courseId: 'crs_203',
    courseCode: 'COM 203',
    courseTitle: 'Database Design & SQL System Management',
    totalClasses: 12,
    attendedClasses: 11,
    percentage: 91.6,
    isEligible: true,
  },
  {
    courseId: 'crs_205',
    courseCode: 'COM 205',
    courseTitle: 'Web Application Development (HTML/CSS/JS)',
    totalClasses: 10,
    attendedClasses: 7,
    percentage: 70.0,
    isEligible: false, // flagged below 75% threshold
  },
];

export const INITIAL_ATTENDANCE_SESSIONS: AttendanceSession[] = [
  {
    id: 'att_sess_live_1',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    date: '2026-07-28',
    topic: 'Tree Data Structures & Heap Sorting',
    totalStudents: 3,
    presentCount: 2,
    sessionCode: '849201',
    isActive: false,
    allowSelfCheckIn: false,
  },
  {
    id: 'att_sess_1',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    date: '2026-07-20',
    topic: 'Arrays, Pointers & Memory Management',
    totalStudents: 3,
    presentCount: 3,
  },
  {
    id: 'att_sess_2',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    date: '2026-07-27',
    topic: 'Singly & Doubly Linked List Operations',
    totalStudents: 3,
    presentCount: 2,
  },
];

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att_rec_1',
    attendanceSessionId: 'att_sess_1',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    present: true,
  },
  {
    id: 'att_rec_2',
    attendanceSessionId: 'att_sess_1',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    present: true,
  },
  {
    id: 'att_rec_3',
    attendanceSessionId: 'att_sess_1',
    studentId: 'usr_student_3',
    studentName: 'Chidimma Nwosu',
    matricNo: 'MAPOLY/ND/CS/2025/0015',
    present: true,
  },
  {
    id: 'att_rec_4',
    attendanceSessionId: 'att_sess_2',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    present: true,
  },
  {
    id: 'att_rec_5',
    attendanceSessionId: 'att_sess_2',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    present: true,
  },
  {
    id: 'att_rec_6',
    attendanceSessionId: 'att_sess_2',
    studentId: 'usr_student_3',
    studentName: 'Chidimma Nwosu',
    matricNo: 'MAPOLY/ND/CS/2025/0015',
    present: false,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  {
    id: 'tt_1',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    courseTitle: 'Data Structures & Algorithms',
    day: 'Monday',
    startTime: '09:00',
    endTime: '11:00',
    venue: 'Computer Lab 2 (New Building)',
    lecturerName: 'Dr. K. A. Mustapha',
    level: 'ND2',
  },
  {
    id: 'tt_2',
    courseId: 'crs_203',
    courseCode: 'COM 203',
    courseTitle: 'Database Design & SQL System Management',
    day: 'Tuesday',
    startTime: '11:00',
    endTime: '13:00',
    venue: 'CS Main Auditorium',
    lecturerName: 'Dr. A. O. Adebayo',
    level: 'ND2',
  },
  {
    id: 'tt_3',
    courseId: 'crs_205',
    courseCode: 'COM 205',
    courseTitle: 'Web Application Development (HTML/CSS/JS)',
    day: 'Thursday',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Software Engineering Lab 1',
    lecturerName: 'Mrs. F. K. Babalola',
    level: 'ND2',
  },
  {
    id: 'tt_4',
    courseId: 'crs_401',
    courseCode: 'COM 411',
    courseTitle: 'Distributed Systems & Cloud Computing Architecture',
    day: 'Wednesday',
    startTime: '10:00',
    endTime: '12:00',
    venue: 'HND Postgraduate Lab',
    lecturerName: 'Dr. A. O. Adebayo',
    level: 'HND2',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_1',
    authorId: 'usr_hod_1',
    authorName: 'Dr. A. O. Adebayo (HOD)',
    authorRole: 'Head of Department',
    scope: 'department',
    title: 'First Semester 2025/2026 Examination Timetable & Verification Notice',
    body: 'All students are requested to ensure their online course registration is signed and approved by their respective level advisers before August 10th. Unregistered students will not be allowed into examination halls.',
    pinned: true,
    createdAt: '2026-07-25T09:00:00Z',
  },
  {
    id: 'ann_2',
    authorId: 'usr_lecturer_1',
    authorName: 'Dr. K. A. Mustapha',
    authorRole: 'Senior Lecturer',
    scope: 'course',
    targetCourseId: 'crs_201',
    targetCourseCode: 'COM 201',
    title: 'COM 201 Practical Assignment Submission Deadline Extended',
    body: 'The Binary Search Trees and Graph Traversal implementation project deadline has been moved to Friday 5:00 PM. Upload your source files through the CSDSIMS Materials Portal.',
    pinned: false,
    createdAt: '2026-07-27T14:30:00Z',
  },
  {
    id: 'ann_3',
    authorId: 'usr_adviser_1',
    authorName: 'Mrs. F. K. Babalola (ND2 Adviser)',
    authorRole: 'Course Adviser',
    scope: 'level',
    targetLevel: 'ND2',
    title: 'ND2 Student Clearance & SIWES Logbook Signing Schedule',
    body: 'ND2 students are to report to Office Room 14 on Thursday between 10:00 AM and 2:00 PM for registration approval verification.',
    pinned: false,
    createdAt: '2026-07-28T11:15:00Z',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat_pq_2024_com201',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    uploadedBy: 'usr_hod_1',
    uploadedByName: 'Dr. A. O. Adebayo (HOD)',
    title: '2024/2025 MAPOLY ND2 Semester Examination Question Paper - Data Structures & Algorithms.pdf',
    description: 'Official Moshood Abiola Polytechnic ND2 First Semester Examination Question Paper with Marking Guide.',
    fileUrl: '#',
    fileSize: '1.4 MB',
    fileType: 'PDF Document',
    topic: 'Official Past Examination Paper',
    category: 'past_question',
    examYear: '2024',
    semester: 'First Semester',
    level: 'ND2',
    downloadCount: 420,
    isOfflineCached: true,
    createdAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'mat_pq_2023_com203',
    courseId: 'crs_203',
    courseCode: 'COM 203',
    uploadedBy: 'usr_lecturer_1',
    uploadedByName: 'Dr. K. A. Mustapha',
    title: '2023/2024 MAPOLY ND2 Semester Examination Question Paper - Database Systems & SQL.pdf',
    description: 'Official MAPOLY Computer Science examination past questions on Relational Algebra & ER Diagrams.',
    fileUrl: '#',
    fileSize: '1.8 MB',
    fileType: 'PDF Document',
    topic: 'Official Past Examination Paper',
    category: 'past_question',
    examYear: '2023',
    semester: 'First Semester',
    level: 'ND2',
    downloadCount: 385,
    isOfflineCached: false,
    createdAt: '2026-07-03T11:30:00Z',
  },
  {
    id: 'mat_pq_2022_com101',
    courseId: 'crs_101',
    courseCode: 'COM 101',
    uploadedBy: 'usr_adviser_1',
    uploadedByName: 'Mrs. F. K. Babalola',
    title: '2022/2023 MAPOLY ND1 Past Examination Questions - Introduction to Computing.pdf',
    description: 'Past examination paper for ND1 freshers covering computer architecture, binary logic gates, and MS Office.',
    fileUrl: '#',
    fileSize: '1.2 MB',
    fileType: 'PDF Document',
    topic: 'Official Past Examination Paper',
    category: 'past_question',
    examYear: '2022',
    semester: 'First Semester',
    level: 'ND1',
    downloadCount: 512,
    isOfflineCached: true,
    createdAt: '2026-07-05T14:15:00Z',
  },
  {
    id: 'mat_1',
    courseId: 'crs_201',
    courseCode: 'COM 201',
    uploadedBy: 'usr_lecturer_1',
    uploadedByName: 'Dr. K. A. Mustapha',
    title: 'Lecture 04: Trees, Heaps, and Graph Structures.pdf',
    description: 'Detailed lecture slides covering binary search trees, AVL trees, Dijkstra algorithm with C implementation examples.',
    fileUrl: '#',
    fileSize: '4.2 MB',
    fileType: 'PDF Document',
    topic: 'Week 4 - Advanced Data Structures',
    category: 'lecture_note',
    level: 'ND2',
    downloadCount: 290,
    isOfflineCached: true,
    createdAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'mat_2',
    courseId: 'crs_203',
    courseCode: 'COM 203',
    uploadedBy: 'usr_hod_1',
    uploadedByName: 'Dr. A. O. Adebayo',
    title: 'Relational Algebra & Normalization Rules (1NF to 5NF).pdf',
    description: 'Reference notes and exercise problems for database schema design and Boyce-Codd normal form.',
    fileUrl: '#',
    fileSize: '2.8 MB',
    fileType: 'PDF Document',
    topic: 'Week 5 - Database Normalization',
    category: 'lecture_note',
    level: 'ND2',
    downloadCount: 310,
    isOfflineCached: false,
    createdAt: '2026-07-18T16:20:00Z',
  },
  {
    id: 'mat_3',
    courseId: 'crs_205',
    courseCode: 'COM 205',
    uploadedBy: 'usr_adviser_1',
    uploadedByName: 'Mrs. F. K. Babalola',
    title: 'Modern Async JavaScript & Practical Web Lab Workbook.pdf',
    description: 'Step-by-step lab tutorial building reactive UI components with Vanilla JS, Fetch API, and CSS Grid.',
    fileUrl: '#',
    fileSize: '1.9 MB',
    fileType: 'PDF Document',
    topic: 'Laboratory Manual',
    category: 'lab_manual',
    level: 'ND2',
    downloadCount: 460,
    isOfflineCached: true,
    createdAt: '2026-07-20T08:45:00Z',
  },
];

export const INITIAL_COURSE_FORMS: CourseFormDoc[] = [
  {
    id: 'cf_1',
    studentId: 'usr_student_1',
    studentName: 'Olamide Adeleke',
    matricNo: 'MAPOLY/ND/CS/2024/0142',
    level: 'ND2',
    fileName: 'MAPOLY_Portal_CourseForm_Olamide_Adeleke.pdf',
    fileSize: '1.4 MB',
    fileUrl: '#',
    uploadedAt: '2026-07-25T14:30:00Z',
    status: 'pending',
  },
  {
    id: 'cf_2',
    studentId: 'usr_student_2',
    studentName: 'Babajide Ogundipe',
    matricNo: 'MAPOLY/HND/CS/2024/0089',
    level: 'HND2',
    fileName: 'MAPOLY_Portal_CourseForm_Babajide_Ogundipe.pdf',
    fileSize: '1.8 MB',
    fileUrl: '#',
    uploadedAt: '2026-07-26T09:15:00Z',
    status: 'verified',
    verifiedBy: 'Mrs. F. K. Babalola',
    verifiedAt: '2026-07-26T11:00:00Z',
  },
];
